### ISSUE TITLE
R package houskeeping in DESCRIPTION file for R pacakge iidda

### ISSUE THREAD

**Issue by mikeroswell** [canmod/iidda-tools#15]
- [x] Right now the version number for RoxygenNote is the dev version of roxygen2 available from GH. Is this necessary? Not sure whether that was set via something like devtools or if it was an intentional choice. 
- [x] Remove 'no visible global function definition' and 'no visible binding for global variable' notes in r cmd check by adding names to a globals.R file that uses the `utils::globalVariables` hack -- sw is chipping away at this
- [x] Document all exported functions or don't export them `W  checking for missing documentation entries`
- [x] properly declare imports from other packages (only one left -- #24)
- [x] Fix Rd files `W checking Rd \usage sections`
- [x] warning from `R CMD check` license is still missing. How do you feel about GPL (>= 3)?
- [x] I am adding some packages that **iidda** already depended on that were flagged by `R CMD check` to `Imports` rather than `Depends`. Is it important to use `Depends`? c.f. https://stackoverflow.com/a/8638902/8400969

**Comment by stevencarlislewalker** [comment]
```
W  checking dependencies in R code (1s)
   '::' or ':::' import not declared from: ‘iidda.api’
```

This particular warning relates to #24

**Comment by stevencarlislewalker** [comment]
Don't care about the roxygen version issue or the 'no visible ...' thing.
