### ISSUE TITLE
want any kind of GH actions to automatically check package(s) on push? (R package idda)

### ISSUE THREAD

**Issue by mikeroswell** [canmod/iidda-tools#16]
Finding several undocumented functions and arguments in the R pacakge **idda**. Do we want to have GH actions check this package on different OSs to verify if it has any issues, and to bug us when we have formal problems like undocumented objects?

**Comment by stevencarlislewalker** [comment]
Yes yes !

**Comment by stevencarlislewalker** [comment]
Implemented
