### ISSUE TITLE
**memoise** dependency in **iidda**: `Imports` or `Depends`

### ISSUE THREAD

**Issue by mikeroswell** [canmod/iidda-tools#20]
itemizing some tickets since they will probably be solved by different people at different times. I'm not familiar with **memoise** yet. Will **iidda** users regularly need to access several functions from **memoise** during regular use? if so, keep in `Depends`. Otherwise move to `Imports` in `DESCRIPTION`.

**Comment by stevencarlislewalker** [comment]
Users won't interact with memoise directly. Should move to imports.
