### ISSUE TITLE
Add missing locations to harmonization_lookup_table

### ISSUE THREAD

**Issue by mikeroswell** [canmod/iidda-tools#23]
Appears to still be missing following tokens:
```
1 NFLD. - T.-N.
2 P.E.I..      
3 NLFD.        
4 NLD.
```
Don't expect this to be comprehensive. This table probably needs to be generated semi-programatically with well-designed regex strings to deal with weird punctuation things like this.

**Comment by stevencarlislewalker** [comment]
Thanks Mike.  Is this blocking you?

**Comment by mikeroswell** [comment]
Not meaningfully.

**Comment by stevencarlislewalker** [comment]
That's good.  I can see that there are more missing locations.

```
> cdi = flexi_filter(
+   strings = ".+",
+   fields = "location",
+   response_type = "columns",
+   data_type = "Communicable Disease Incidence"
+ )
> saved_locations_iso = read_csv("tracking/locations_ISO.csv")                     
> all_locations_iso = (cdi
+   %>% select(location)
+   %>% distinct
+ )
> all_locations_iso$location[which(!all_locations_iso$location %in% saved_locations_iso$location)]
 [1] "Que."    "Ont."    "Man."    "Sask."   "Alta."   "P.E.I.." "NLFD."   "NLD."   
 [9] "FNLD."   "NFLD"  
```

I'm going to add these now.

I think the 'right' way to do it is to _automatically_ add locations that exist in the repo but not in the lookup table, but add these locations without the corresponding iso codes. Then _manually_ add the iso codes. This is a very easy manual job. I'll do that now.

**Comment by stevencarlislewalker** [comment]
One thing that I'm confused about though, is that I see `NFLD. - T.-N.` in the lookup table.

**Comment by mikeroswell** [comment]
Guessing it's hiding spaces or something. I wrote this very clunky string substitution and that issue disappeared for me: 
```{r}
# string simplification
fix_loc <- function(loc){
  gsub("\\.", "", gsub("-", "", gsub(" ", "", tolower(loc))))
}
```

**Comment by stevencarlislewalker** [comment]
That's good.

I think I fixed the issue in general now with.
https://github.com/davidearn/data_work/commit/6b06fc51167dda59b9070c25aee403b70b1b5863
https://github.com/davidearn/data_work/commit/37cf0f6a906f004de0b79e68d7c8a042e12add07
https://github.com/davidearn/data_work/commit/97db3064d2d56ff522939331ce6d973ca317a491
